#!/usr/bin/env bash
cd "${0%/*}/.."

DIST=target/dist
SCALA=target/scala-2.11
rm -rf $DIST
mkdir -p $DIST
cp index.html $DIST
mkdir -p $DIST/$SCALA
for file in $SCALA/*.js; do cp $file $DIST/$SCALA; done
surge $DIST spiral-examples.surge.sh